task_manager/tasks/urls.py
from django.urls import path

from task_manager.tasks import views


urlpatterns = [
    path('', views.Tasks.as_view(), name='tasks'),
    path('create/', views.TaskCreate.as_view(), name='task_create'),
    path('<int:pk>/', views.TaskView.as_view(), name='task_detail'),
    path('<int:pk>/update/', views.TaskUpdate.as_view(), name='task_update'),
    path('<int:pk>/delete/', views.TaskDelete.as_view(), name='task_delete'),
]

task_manager/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

from task_manager import views


schema_view = get_schema_view(
    openapi.Info(
        title="Task Manager API",
        default_version="v1",
        description="Useful tool for both personal and team projects",
        contact=openapi.Contact(email="sidai@bk.ru"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    # templates
    path("admin/", admin.site.urls),
    path("", views.HomePageView.as_view(), name="home"),
    path("login/", views.Login.as_view(), name="login"),
    path("logout/", views.Logout.as_view(), name="logout"),
    path("users/", include("task_manager.users.urls")),
    path("statuses/", include("task_manager.statuses.urls")),
    path("tasks/", include("task_manager.tasks.urls")),
    path("labels/", include("task_manager.labels.urls")),
    # api
    path("api/v1/", include("task_manager.api.urls")),
    path("api-auth", include("rest_framework.urls")),
    path("api/v1/rest-auth", include("rest_auth.urls")),
    path("api/v1/rest-auth/registration", include("rest_auth.registration.urls")),
    # api docs
    re_path(
        r"^swagger(?P<format>\.json|\.yaml)$",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    re_path(
        r"^swagger/$",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    re_path(
        r"^redoc/$", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"
    ),
]

task_manager/tasks/models.py
from django.db import models
from django.contrib.auth.models import User

from task_manager.statuses.models import Status
from task_manager.labels.models import Label


class Task(models.Model):
    name = models.CharField(max_length=150, unique=True)
    description = models.CharField(max_length=150)
    created_at = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name="author"
        )
    executor = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name="executor",
        blank=True
        )
    status = models.ForeignKey(
        Status,
        on_delete=models.PROTECT,
        blank=True
        )
    labels = models.ManyToManyField(
        Label,
        blank=True
        )

    def __str__(self):
        return self.name

task_manager/tasks/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views import View
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse

from task_manager.tasks.models import Task
from task_manager.labels.models import Label
from task_manager.statuses.models import Status
from task_manager.tasks.utils import TaskMixin, TaskFilter


class TaskView(View):
    """View that collects all data concerning the chosen task
    and then renders a card with task info."""

    def get(self, request, pk):
        task_selected = (
            Task.objects.select_related("executor", "status", "author")
            .prefetch_related("labels")
            .get(pk=pk)
        )
        return render(request, "task-detail.html", {"task": task_selected})


class Tasks(LoginRequiredMixin, View):
    """View that shows list of tasks. Allows filtration through GET params.
    Full list of tasks is shown by default."""

    def get(self, request):
        tasks = Task.objects.select_related("executor", "status", "author").all()
        tasks = TaskFilter._filter(self, request, tasks)
        labels = Label.objects.all()
        statuses = Status.objects.all()
        users = User.objects.all()

        return render(
            request,
            "task-list.html",
            {"tasks": tasks, "users": users, "statuses": statuses, "labels": labels},
        )


class TaskCreate(LoginRequiredMixin,
                 SuccessMessageMixin,
                 TaskMixin,
                 CreateView):
    template_name = "task-create.html"
    success_message = "Задача успешно создана"


class TaskUpdate(LoginRequiredMixin,
                 SuccessMessageMixin,
                 TaskMixin,
                 UpdateView):
    template_name = "task-update.html"
    success_message = "Задача успешно изменена"


class TaskDelete(LoginRequiredMixin,
                 SuccessMessageMixin,
                 TaskMixin,
                 DeleteView):
    template_name = "task-delete.html"
    success_message = "Задача успешно удалена"

    def get(self, request, pk):
        self.object = self.get_object()
        if self.object.author.pk == request.user.pk:
            return render(request, "task-delete.html", {'task': self.object})
        else:
            messages.error(request, "Задачу может удалить только её автор")
            return redirect(reverse('tasks'))

task_manager/tasks/templates/task-create.html
{% extends "base.html" %} {% block content %}

<h1 class="my-4"></h1>
<form action="{% url 'task_create' %}" method="post">
  {% csrf_token %}
  <div class="form-group">
    <label for="id_name">Имя</label
    ><input
      type="text"
      name="name"
      maxlength="150"
      class="form-control"
      placeholder="Имя"
      title=""
      required
      id="id_name"
    />
  </div>
  <div class="form-group">
    <label for="id_description">Описание</label
    ><textarea
      name="description"
      cols="40"
      rows="10"
      class="form-control"
      placeholder="Описание"
      title=""
      required id="id_description"
    ></textarea>
  </div>
  <div class="form-group">
    <input type="hidden" name="author" value="{{ user.pk }}" />
  </div>
  <div class="form-group">
    <label for="id_status">Статус</label>
    <select name="status" class="form-control" title="" required id="id_status">
      <option value="" selected>---------</option>
      {% for status in statuses %}
      <option value="{{ status.pk }}">{{ status.name }}</option>
      {% endfor %}
    </select>
  </div>
  <div class="form-group">
    <label for="id_executor">Исполнитель</label>
    <select name="executor" class="form-control" title="" required id="id_executor">
      <option value="" selected>---------</option>
      {% for user in users %}
      <option value="{{ user.pk }}">{{ user.first_name }} {{ user.last_name }} </option>
      {% endfor %}
    </select>
  </div>
  <div class="form-group">
    <label for="id_labels">Метки</label>
    <select name="labels" class="form-control" title="" id="id_labels" multiple>
      {% for label in labels %}
      <option value="{{ label.pk }}">{{ label.name }}</option>
      {% endfor %}
    </select>
  </div>
  <div class="form-group">
    <input class="btn btn-primary" type="submit" value="Создать" />
  </div>
</form>

{% endblock content %}

task_manager/tasks/templates/task-delete.html
{% extends "base.html" %} {% block content %}

<h1 class="my-4">Удаление задачи</h1>

<p>Вы уверены, что хотите удалить {{ task.name }}?</p>

<form action="{% url 'task_delete' task.pk %}" method="post">
  {% csrf_token %}
  <input class="btn btn-danger" type="submit" value="Да, удалить" />
</form>

{% endblock content %}

task_manager/tasks/templates/task-detail.html
{% extends "base.html" %}

{% block content %}
<div class="container wrapper flex-grow-1">
    <h1 class="my-4">
      
Просмотр задачи

    </h1>

<div class="card">
<div class="card-header bg-secondary text-white">
  <h2>{{ task.name }}</h2>
</div>
<div class="card-body bg-light">
  <p>{{ task.description }}</p>
  <hr>
  <div class="container">
    <div class="row p-1">
      <div class="col">Автор</div>
      <div class="col">{{ task.author.first_name }} {{ task.author.last_name }}</div>
    </div>
    <div class="row p-1">
      <div class="col">Исполнитель</div>
      <div class="col">{{ task.executor.first_name }} {{ task.executor.last_name }}</div>
    </div>
    <div class="row p-1">
      <div class="col">Статус</div>
      <div class="col">{{ task.status.name }}</div>
    </div>
    <div class="row p-1">
      <div class="col">Дата создания</div>
      <div class="col">{{ task.created_at }}</div>
    </div>
    <div class="row p-1">
      <div class="col">
        <h6>Метки:</h6>
        <ul>
          {% for label in task.labels.all %}
          {{ label.name }}
          {% endfor %}
        </ul>
      </div>
    </div>
    <div class="row p-1">
      <div class="col">
        <a href="{% url 'task_update' task.pk %}">Изменить</a>
        <br>
        <a href="{% url 'task_delete' task.pk %}">Удалить</a>
      </div>
    </div>
  </div>
</div>
</div>

  </div>
{% endblock content %}

task_manager/tasks/templates/task-list.html
{% extends "base.html" %} {% block content %}

<h1 class="my-4">Задачи</h1>

<a class="nav-link" href="{% url 'task_create' %}">Создать задачу</a>


<div class="card mb-3">
    <div class="card-body bg-light">
    <form class="form-inline center" method="get">
        <div class="form-group"><label for="id_status">Статус</label><div class="ml-2 mr-3"><select name="status" class="form-control" title="" id="id_status">
    <option value="" selected>---------</option>
    {% for status in statuses %} 
    <option value="{{ status.pk }}">{{ status.name }}</option>
    {% endfor %}

</select></div></div>
        <div class="form-group"><label for="id_executor">Исполнитель</label><div class="mr-3 ml-2"><select name="executor" class="form-control" title="" id="id_executor">
          <option value="" selected>---------</option>
          {% for user in users %} 
          <option value="{{ user.pk }}">{{ user.first_name }} {{ user.last_name }}</option>
          {% endfor %}

</select></div></div>
        <div class="form-group"><label for="id_label">Метка</label><div class="mr-3 ml-2"><select name="label" class="form-control" title="" id="id_label">
          <option value="" selected>---------</option>
          {% for label in labels %} 
          <option value="{{ label.pk }}">{{ label.name }}</option>
          {% endfor %}

</select></div></div>
        <div class="form-group"><div class="mr-3"><div class="form-check"><input type="checkbox" name="self_tasks" class="form-check-input" id="id_self_tasks"><label class="form-check-label" for="id_self_tasks">Только свои задачи</label></div></div></div>
        <div class="form-group">
        <input class="btn btn-primary" type="submit" value="Показать">
        </div>
    </form>
    </div>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Имя</th>
      <th>Статус</th>
      <th>Автор</th>
      <th>Исполнитель</th>
      <th>Дата создания</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    {% for task in tasks %}
    <tr>
      <td>{{ task.pk }}</td>
      <td>
        <a href="{% url 'task_detail' task.pk %}">{{ task.name }}</a>
      </td>
      <td>{{ task.status.name }}</td>
      <td>{{ task.author.first_name }} {{ task.author.last_name }}</td>
      <td>{{ task.executor.first_name }} {{ task.executor.last_name }}</td>
      <td>{{ task.created_at }}</td>
      <td>
        <a href="{% url 'task_update' task.pk %}">Изменить</a>
        <br />
        <a href="{% url 'task_delete' task.pk %}">Удалить</a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock content %}

task_manager/tasks/templates/task-page.html
{% extends "base.html" %}

{% block content %}
<div class="container wrapper flex-grow-1">
    <h1 class="my-4">
      
Просмотр задачи

    </h1>
    
<div class="card">
<div class="card-header bg-secondary text-white">
  <h2>{{ task.name }}</h2>
</div>
<div class="card-body bg-light">
  <p>{{ task.description }}</p>
  <hr>
  <div class="container">
    <div class="row p-1">
      <div class="col">Автор</div>
      <div class="col">{{ task.author.first_name }} {{ task.author.last_name }}</div>
    </div>
    <div class="row p-1">
      <div class="col">Исполнитель</div>
      <div class="col">{{ task.executor.first_name }} {{ task.executor.last_name }}</div>
    </div>
    <div class="row p-1">
      <div class="col">Статус</div>
      <div class="col">{{ task.status.name }}</div>
    </div>
    <div class="row p-1">
      <div class="col">Дата создания</div>
      <div class="col">{{ task.created_at }}</div>
    </div>
    <div class="row p-1">
      <div class="col">
        <h6>Метки:</h6>
        <ul>
          {% for label in task.labels.all %}
          {{ label.name }}
          {% endfor %}
        </ul>
      </div>
    </div>
    <div class="row p-1">
      <div class="col">
        <a href="{% url 'tasks_update' task.pk %}">Изменить</a>
        <br>
        <a href="{% url 'tasks_delete' task.pk %}">Удалить</a>
      </div>
    </div>
  </div>
</div>
</div>

  </div>
{% endblock content %}

task_manager/tasks/templates/task-update.html
{% extends "base.html" %}

{% block content %}

<h1 class="my-4">Изменить задачу</h1>
<form action="{% url 'task_update' task.pk %}" method="post">
  {% csrf_token %}
  <div class="form-group">
    <label for="id_name">Имя</label
    ><input
      type="text"
      name="name"
      maxlength="150"
      class="form-control"
      placeholder="Имя"
      title=""
      required
      id="id_name"
      value="{{ task.name }}"
    />
  </div>
  <div class="form-group">
    <label for="id_description">Описание</label
    ><textarea
      name="description"
      cols="40"
      rows="10"
      class="form-control"
      placeholder="Описание"
      title=""
      required id="id_description"
    >{{ task.description }}</textarea>
  </div>
  <div class="form-group">
    <input type="hidden" name="author" value="{{ user.pk }}" />
  </div>
  <div class="form-group">
    <label for="id_status">Статус</label>
    <select name="status" class="form-control" title="" required id="id_status">
      {% if not task.status_id %}
      <option value="" selected>---------</option>
      {% else %}
      <option value="">---------</option>
      {% endif %}

      {% for status in statuses %} 
        {% if status.pk != task.status.pk %}
        <option value="{{ status.pk }}">{{ status.name }}</option>
        {% else %}
        <option value="{{ status.pk }}" selected>{{ status.name }}</option>
        {% endif %}
      {% endfor %}
    </select>
  </div>
  <div class="form-group">
    <label for="id_executor">Исполнитель</label>
    <select name="executor" class="form-control" title="" required id="id_executor">
      {% if not task.executor_id %}
      <option value="" selected>---------</option>
      {% else %}
      <option value="">---------</option>
      {% endif %}

      {% for user in users %}
        {% if user.pk != task.executor.pk %}
        <option value="{{ user.pk }}">{{ user.first_name }} {{ user.last_name }}</option>
        {% else %}
        <option value="{{ user.pk }}" selected>{{ user.first_name }} {{ user.last_name }}</option>
        {% endif %}
      {% endfor %}
    </select>
  </div>
  <div class="form-group">
    <label for="id_labels">Метки</label>
    <select name="labels" class="form-control" title="" id="id_labels" multiple>
      {% if not task.labels_id %}
      <option value="" selected>---------</option>
      {% else %}
      <option value="">---------</option>
      {% endif %}

      {% for label in labels %} 
        {% if label.pk == task.labels.id %}
        <option value="{{ label.pk }}" selected>{{ label.name }}</option>
        {% else %}
        <option value="{{ label.pk }}">{{ label.name }}</option>
        {% endif %}
      {% endfor %}
    </select>
  </div>
  <div class="form-group">
    <input class="btn btn-primary" type="submit" value="Обновить" />
  </div>
</form>

{% endblock content %}