task_manager/api/urls.py
from django.urls import path

from task_manager.api import views


urlpatterns = [
    # path("admin/", admin.site.urls),
    path("users/", views.UserList.as_view()),
    path("users/<int:pk>/", views.UserDetail.as_view()),
    path("labels/", views.LabelList.as_view()),
    path("labels/<int:pk>/", views.LabelDetail.as_view()),
    path("statuses/", views.StatusList.as_view()),
    path("statuses/<int:pk>/", views.StatusDetail.as_view()),
    path("tasks/", views.TaskList.as_view()),
    path("tasks/<int:pk>/", views.TaskDetail.as_view()),
]

task_manager/tasks/urls.py
from django.urls import path

from task_manager.tasks import views


urlpatterns = [
    path('', views.Tasks.as_view(), name='tasks'),
    path('create/', views.TaskCreate.as_view(), name='task_create'),
    path('<int:pk>/', views.TaskView.as_view(), name='task_detail'),
    path('<int:pk>/update/', views.TaskUpdate.as_view(), name='task_update'),
    path('<int:pk>/delete/', views.TaskDelete.as_view(), name='task_delete'),
]

task_manager/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

from task_manager import views


schema_view = get_schema_view(
    openapi.Info(
        title="Task Manager API",
        default_version="v1",
        description="Useful tool for both personal and team projects",
        contact=openapi.Contact(email="sidai@bk.ru"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    # templates
    path("admin/", admin.site.urls),
    path("", views.HomePageView.as_view(), name="home"),
    path("login/", views.Login.as_view(), name="login"),
    path("logout/", views.Logout.as_view(), name="logout"),
    path("users/", include("task_manager.users.urls")),
    path("statuses/", include("task_manager.statuses.urls")),
    path("tasks/", include("task_manager.tasks.urls")),
    path("labels/", include("task_manager.labels.urls")),
    # api
    path("api/v1/", include("task_manager.api.urls")),
    path("api-auth", include("rest_framework.urls")),
    path("api/v1/rest-auth", include("rest_auth.urls")),
    path("api/v1/rest-auth/registration", include("rest_auth.registration.urls")),
    # api docs
    re_path(
        r"^swagger(?P<format>\.json|\.yaml)$",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    re_path(
        r"^swagger/$",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    re_path(
        r"^redoc/$", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"
    ),
]

task_manager/users/urls.py
from django.urls import path

from task_manager.users import views


urlpatterns = [
    path("", views.Users.as_view(), name="users"),
    path("create/", views.CreateUser.as_view(), name="user_create"),
    path("<int:pk>/update/", views.UpdateUser.as_view(), name="user_update"),
    path("<int:pk>/delete/", views.DeleteUser.as_view(), name="user_delete"),
]

task_manager/labels/models.py
from django.db import models


class Label(models.Model):
    name = models.CharField(max_length=150, unique=True)
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

task_manager/statuses/models.py
from django.db import models


class Status(models.Model):
    name = models.CharField(max_length=150, unique=True)
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

task_manager/tasks/models.py
from django.db import models
from django.contrib.auth.models import User

from task_manager.statuses.models import Status
from task_manager.labels.models import Label


class Task(models.Model):
    name = models.CharField(max_length=150, unique=True)
    description = models.CharField(max_length=150)
    created_at = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name="author"
        )
    executor = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name="executor",
        blank=True
        )
    status = models.ForeignKey(
        Status,
        on_delete=models.PROTECT,
        blank=True
        )
    labels = models.ManyToManyField(
        Label,
        blank=True
        )

    def __str__(self):
        return self.name

task_manager/forms.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(required=True)
    password = forms.CharField(widget=forms.PasswordInput, required=True)

task_manager/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class NewUserForm(UserCreationForm):
    first_name = forms.CharField(max_length=150, required=True)
    last_name = forms.CharField(max_length=150, required=True)

    class Meta:
        model = User
        fields = ["first_name", "last_name",
                  "username", "password1", "password2"]


class UpdateUserForm(forms.ModelForm):
    first_name = forms.CharField(max_length=150, required=True)
    last_name = forms.CharField(max_length=150, required=True)
    password1 = forms.CharField(widget=forms.PasswordInput, required=True)
    password2 = forms.CharField(widget=forms.PasswordInput, required=True)

    class Meta:
        model = User
        fields = ["first_name", "last_name",
                  "username", "password1", "password2"]

task_manager/api/views.py
from rest_framework import generics
from rest_framework.permissions import IsAuthenticated, AllowAny, IsAdminUser
from django.contrib.auth.models import User

from task_manager.labels.models import Label
from task_manager.statuses.models import Status
from task_manager.tasks.models import Task
from .permissions import IsAuthorOrReadOnly, IsCurrentUser
from .serializers import (
    UserSerializer,
    LabelSerializer,
    StatusSerializer,
    TaskSerializer,
)


class UserList(generics.ListAPIView):
    permission_classes = (AllowAny,)
    queryset = User.objects.all()
    serializer_class = UserSerializer


class UserDetail(generics.RetrieveUpdateDestroyAPIView):
    permission_classes = (IsCurrentUser or IsAdminUser,)
    queryset = User.objects.all()
    serializer_class = UserSerializer


class LabelList(generics.ListCreateAPIView):
    permission_classes = (IsAuthenticated,)
    queryset = Label.objects.all()
    serializer_class = LabelSerializer


class LabelDetail(generics.RetrieveUpdateDestroyAPIView):
    permission_classes = (IsAuthenticated,)
    queryset = Label.objects.all()
    serializer_class = LabelSerializer


class StatusList(generics.ListCreateAPIView):
    permission_classes = (IsAuthenticated,)
    queryset = Status.objects.all()
    serializer_class = StatusSerializer


class StatusDetail(generics.RetrieveUpdateDestroyAPIView):
    permission_classes = (IsAuthenticated,)
    queryset = Status.objects.all()
    serializer_class = StatusSerializer


class TaskList(generics.ListCreateAPIView):
    permission_classes = (IsAuthenticated,)
    queryset = Task.objects.all()
    serializer_class = TaskSerializer


class TaskDetail(generics.RetrieveUpdateDestroyAPIView):
    permission_classes = (IsAuthorOrReadOnly or IsAdminUser,)
    queryset = Task.objects.all()
    serializer_class = TaskSerializer

task_manager/labels/views.py
from django.shortcuts import render
from django.views.generic.edit import FormView, CreateView, UpdateView, DeleteView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin

from task_manager.labels.models import Label
from task_manager.labels.utils import LabelMixin


class Labels(LoginRequiredMixin, FormView):
    def get(self, request):
        labels = Label.objects.all()
        return render(request, "labels.html", {"labels": labels})


class LabelCreate(LoginRequiredMixin, SuccessMessageMixin, LabelMixin, CreateView):
    template_name = "label-create.html"
    success_message = "Метка успешно создана"


class LabelUpdate(LoginRequiredMixin, SuccessMessageMixin, LabelMixin, UpdateView):
    template_name = "label-update.html"
    success_message = "Метка успешно изменена"


class LabelDelete(LoginRequiredMixin, SuccessMessageMixin, LabelMixin, DeleteView):
    template_name = "label-delete.html"
    success_message = "Метка успешно удалена"

task_manager/statuses/views.py
from django.shortcuts import render
from django.views.generic.edit import FormView, CreateView, UpdateView, DeleteView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin

from task_manager.statuses.models import Status
from task_manager.statuses.utils import StatusMixin


class Statuses(LoginRequiredMixin, FormView):
    def get(self, request):
        statuses = Status.objects.all()
        return render(request, "statuses.html", {"statuses": statuses})


class StatusCreate(LoginRequiredMixin,
                   SuccessMessageMixin,
                   StatusMixin,
                   CreateView):
    template_name = "status-create.html"
    success_message = "Статус успешно создан"


class StatusUpdate(LoginRequiredMixin,
                   SuccessMessageMixin,
                   StatusMixin,
                   UpdateView):
    template_name = "status-update.html"
    success_message = "Статус успешно изменён"


class StatusDelete(LoginRequiredMixin,
                   SuccessMessageMixin,
                   StatusMixin,
                   DeleteView):
    template_name = "status-delete.html"
    success_message = "Статус успешно удалён"

task_manager/tasks/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views import View
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse

from task_manager.tasks.models import Task
from task_manager.labels.models import Label
from task_manager.statuses.models import Status
from task_manager.tasks.utils import TaskMixin, TaskFilter


class TaskView(View):
    """View that collects all data concerning the chosen task
    and then renders a card with task info."""

    def get(self, request, pk):
        task_selected = (
            Task.objects.select_related("executor", "status", "author")
            .prefetch_related("labels")
            .get(pk=pk)
        )
        return render(request, "task-detail.html", {"task": task_selected})


class Tasks(LoginRequiredMixin, View):
    """View that shows list of tasks. Allows filtration through GET params.
    Full list of tasks is shown by default."""

    def get(self, request):
        tasks = Task.objects.select_related("executor", "status", "author").all()
        tasks = TaskFilter._filter(self, request, tasks)
        labels = Label.objects.all()
        statuses = Status.objects.all()
        users = User.objects.all()

        return render(
            request,
            "task-list.html",
            {"tasks": tasks, "users": users, "statuses": statuses, "labels": labels},
        )


class TaskCreate(LoginRequiredMixin,
                 SuccessMessageMixin,
                 TaskMixin,
                 CreateView):
    template_name = "task-create.html"
    success_message = "Задача успешно создана"


class TaskUpdate(LoginRequiredMixin,
                 SuccessMessageMixin,
                 TaskMixin,
                 UpdateView):
    template_name = "task-update.html"
    success_message = "Задача успешно изменена"


class TaskDelete(LoginRequiredMixin,
                 SuccessMessageMixin,
                 TaskMixin,
                 DeleteView):
    template_name = "task-delete.html"
    success_message = "Задача успешно удалена"

    def get(self, request, pk):
        self.object = self.get_object()
        if self.object.author.pk == request.user.pk:
            return render(request, "task-delete.html", {'task': self.object})
        else:
            messages.error(request, "Задачу может удалить только её автор")
            return redirect(reverse('tasks'))

task_manager/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.db.models import ProtectedError
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View

from task_manager.users.forms import NewUserForm, UpdateUserForm


class Users(View):
    def get(self, request):
        User = get_user_model()
        users = User.objects.all()
        return render(request, "users.html", {"users": users})


class CreateUser(View):
    def get(self, request):
        form = NewUserForm()
        return render(request, "user-create.html", {"form": form})

    def post(self, request):
        form = NewUserForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data.get("first_name")
            last_name = form.cleaned_data.get("last_name")
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password1")

            user = User.objects.create_user(
                username=username,
                first_name=first_name,
                last_name=last_name,
                password=password,
            )
            messages.success(request, "Пользователь успешно зарегистрирован")
            return redirect("/login/", username=user.username)
        else:
            return render(request, "user-create.html", {"form": form})


class UpdateUser(LoginRequiredMixin, SuccessMessageMixin, View):
    redirect_field_name = None

    def get(self, request, pk):
        if pk == request.user.id and request.user.is_authenticated:
            return render(request, "user-update.html", {"user": request.user})
        elif not request.user.is_authenticated:
            messages.error(request, "Вы не авторизованы! Пожалуйста, выполните вход.")
            return redirect("/login/")
        else:
            messages.error(
                request, "У вас нет прав для изменения другого пользователя."
            )
            return redirect("/users/")

    def post(self, request, pk):
        if pk == request.user.id and request.user.is_authenticated:
            user = User.objects.get(pk=pk)
            form = UpdateUserForm(data=request.POST, instance=user)
            if form.is_valid():
                user = form.save(commit=False)
                user.save()
                messages.success(request, "Пользователь успешно изменён")
                return redirect("/users/")
            else:
                render(request, "user-update.html", {"user": request.user})
        else:
            messages.error(
                request, "У вас нет прав для изменения другого пользователя."
            )


class DeleteUser(LoginRequiredMixin, View):
    redirect_field_name = None

    def get(self, request, pk):
        if pk == request.user.id:
            return render(request, "user-delete.html", {"user": request.user})
        else:
            messages.error(
                request, "У вас нет прав для изменения другого пользователя."
            )
            return redirect("/users/")

    def post(self, request, pk):
        if pk == request.user.id:
            user = User.objects.get(pk=pk)
            if user:
                try:
                    user.delete()
                    messages.success(request, "Пользователь успешно удалён")
                except ProtectedError:
                    messages.error(
                        request,
                        "Невозможно удалить пользователя, потому что он используется",
                    )
        else:
            messages.error(
                request, "У вас нет прав для изменения другого пользователя."
            )

        return redirect("/users/")

task_manager/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import login, logout, authenticate
from django.contrib.messages.views import SuccessMessageMixin
from django.views import View

from task_manager.forms import LoginForm


class HomePageView(View):
    def get(self, request):
        return render(request, "home.html")


class Login(SuccessMessageMixin, View):
    def get(self, request):
        form = LoginForm()
        return render(request, "login.html", {"form": form})

    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    messages.success(request, "Вы залогинены")
                    return redirect("/")

            messages.error(
                request,
                "Пожалуйста, введите правильные имя пользователя и пароль. "
                "Оба поля могут быть чувствительны к регистру.",
            )
            return render(request, "login.html", {"form": form})


class Logout(View):
    def post(self, request):
        logout(request)
        messages.info(request, "Вы разлогинены")
        return redirect("/")

task_manager/templates/base.html
<!DOCTYPE html>
<html lang="ru-ru">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Менеджер задач</title>
    <link crossorigin="anonymous" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" rel="stylesheet">
    <script crossorigin="anonymous" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script crossorigin="anonymous" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script crossorigin="anonymous" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  </head>
  <body class="d-flex flex-column min-vh-100">
    <nav class="navbar navbar-expand-lg navbar-light bg-light mb-3">
      <a class="navbar-brand" href="/">Менеджер задач</a>
      <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarToggleExternalContent">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarToggleExternalContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users' %}">Пользователи</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'statuses' %}">Статусы</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'labels' %}">Метки</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'tasks' %}">Задачи</a>
          </li>
          {% endif %}
        </ul>

        {% if user.is_authenticated %}
        <form action="{% url 'logout' %}" method="post">{% csrf_token %}
          <input class="btn nav-link" type="submit" value="Выход">
        </form>
        {% else %}
        <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">Вход</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'user_create' %}">Регистрация</a>
            </li>
        </ul>
        {% endif %}
      </div>
    </nav>

      <main role="main" class="container"  >
        {% if messages %}
          {% for message in messages %}
            {% if message.tags == "error"%}
            <div class="alert alert-danger">
              {{ message }}
            </div>
            {% else %}
            <div class="alert alert-success">
              {{ message }}
            </div>
            {% endif %}
          {% endfor %}
        {% endif %}

      {% block content %}

      {% endblock content %}
    </div>
  </body>
</html>

task_manager/templates/create-user.html
{% extends "base.html" %}

{% block content %}

      <h1 class="my-4">
      Регистрация
      </h1>

<form action="/users/create/" method="post">{% csrf_token %}
  <div class="form-group"><label for="id_first_name">Имя</label><input type="text" name="first_name" maxlength="150" class="form-control" placeholder="Имя" title="" required id="id_first_name"></div>
<div class="form-group"><label for="id_last_name">Фамилия</label><input type="text" name="last_name" maxlength="150" class="form-control" placeholder="Фамилия" title="" required id="id_last_name"></div>
<div class="form-group"><label for="id_username">Имя пользователя</label><input type="text" name="username" maxlength="150" autofocus class="form-control" placeholder="Имя пользователя" title="Обязательное поле. Не более 150 символов. Только буквы, цифры и символы @/./+/-/_." required id="id_username">
    <small class="form-text text-muted">Обязательное поле. Не более 150 символов. Только буквы, цифры и символы @/./+/-/_.</small>

</div>
<div class="form-group"><label for="id_password1">Пароль</label><input type="password" name="password1" autocomplete="new-password" class="form-control" placeholder="Пароль" title="Ваш пароль должен содержать как минимум 3 символа." required id="id_password1">
    <small class="form-text text-muted"><ul><li>Ваш пароль должен содержать как минимум 3 символа.</li></ul></small>

</div>
<div class="form-group"><label for="id_password2">Подтверждение пароля</label><input type="password" name="password2" autocomplete="new-password" class="form-control" placeholder="Подтверждение пароля" title="Для подтверждения введите, пожалуйста, пароль ещё раз." required id="id_password2">
    <small class="form-text text-muted">Для подтверждения введите, пожалуйста, пароль ещё раз.</small>

</div>
  <div class="form-group">
    <input class="btn btn-primary" type="submit" value="Зарегистрировать">
  </div>
</form>
{% endblock content %}

task_manager/templates/delete-user.html
{% extends "base.html" %}

{% block content %}

      <h1 class="my-4">
        
Удаление пользователя

      </h1>
      
<p>Вы уверены, что хотите удалить {{ user.first_name }} {{ user.last_name }}?</p>

<form action="/users/{{ user.pk }}/delete/" method="post">{% csrf_token %}
  <input class="btn btn-danger" type="submit" value="Да, удалить">
</form>

{% endblock content %}

task_manager/templates/home.html
{% extends "base.html" %}

{% block content %}

<h1 class="my-4"></h1>
<div class="card">
  <div class="card-body p-5 bg-light">
    <div class="display-4">Менеджер задач</div>
    <hr>
    <div class="display-5">Система управления задачами для работы в команде</div>
    <hr>
    <a class="btn btn-primary btn-lg" href="{% url 'user_create' %}">Начать</a>
  </div>
</div>
</div>
</body>

</html>

{% endblock content %}

task_manager/templates/index.html
{% extends "base.html" %}

{% block content %}

<h1 class="my-4"></h1>
<div class="card">
  <div class="card-body p-5 bg-light">
    <div class="display-4">Привет от Хекслета!</div>
    <p class="lead">Практические курсы по программированию</p>
    <hr>
    <a class="btn btn-primary btn-lg" href="https://ru.hexlet.io">Узнать больше</a>
  </div>
</div>
    </div>
  </body>
</html>

{% endblock content %}

task_manager/templates/login.html
{% extends "base.html" %} {% block content %}
<h1 class="my-4">Вход</h1>
<form action="{% url 'login' %}" method="post">
  {% csrf_token %}
  <div class="form-group">
    <label for="id_username">Имя пользователя</label
    ><input
      type="text"
      name="username"
      autofocus
      autocapitalize="none"
      autocomplete="username"
      maxlength="150"
      class="form-control"
      placeholder="Имя пользователя"
      title=""
      required
      id="id_username"
    />
  </div>
  <div class="form-group">
    <label for="id_password">Пароль</label
    ><input
      type="password"
      name="password"
      autocomplete="current-password"
      class="form-control"
      placeholder="Пароль"
      title=""
      required
      id="id_password"
    />
  </div>
  <div class="form-group">
    <input class="btn btn-primary" type="submit" value="Войти" />
  </div>
</form>
{% endblock content %}

task_manager/templates/update-user.html
{% extends "base.html" %}

{% block content %}
<h1 class="my-4">
Изменение пользователя
</h1>

<form action="/users/{{ user.pk }}/update/" method="post">{% csrf_token %}
  <div class="form-group"><label for="id_first_name">Имя</label><input type="text" name="first_name" value="{{ user.first_name }}" maxlength="150" class="form-control" placeholder="Имя" title="" required id="id_first_name"></div>
<div class="form-group"><label for="id_last_name">Фамилия</label><input type="text" name="last_name" value="{{ user.last_name }}" maxlength="150" class="form-control" placeholder="Фамилия" title="" required id="id_last_name"></div>
<div class="form-group"><label for="id_username">Имя пользователя</label><input type="text" name="username" value="{{ user.username }}" maxlength="150" autofocus class="form-control" placeholder="Имя пользователя" title="Обязательное поле. Не более 150 символов. Только буквы, цифры и символы @/./+/-/_." required id="id_username">
    <small class="form-text text-muted">Обязательное поле. Не более 150 символов. Только буквы, цифры и символы @/./+/-/_.</small>

</div>
<div class="form-group"><label for="id_password1">Пароль</label><input type="password" name="password1" autocomplete="new-password" class="form-control" placeholder="Пароль" title="Ваш пароль должен содержать как минимум 3 символа." required id="id_password1">
    <small class="form-text text-muted"><ul><li>Ваш пароль должен содержать как минимум 3 символа.</li></ul></small>

</div>
<div class="form-group"><label for="id_password2">Подтверждение пароля</label><input type="password" name="password2" autocomplete="new-password" class="form-control" placeholder="Подтверждение пароля" title="Для подтверждения введите, пожалуйста, пароль ещё раз." required id="id_password2">
    <small class="form-text text-muted">Для подтверждения введите, пожалуйста, пароль ещё раз.</small>

</div>
  <div class="form-group">
    <input class="btn btn-primary" type="submit" value="Изменить">
  </div>
</form>

{% endblock content %}